### ISSUE TITLE
tclgd does not work with Tcl/Tk 8.7.a5

### ISSUE THREAD

**Issue by PaulObermeier** [flightaware/tcl.gd#7]
Apply the following changes to make tclgd work with Tcl/Tk 8.7.a5:

Changed load functionality: 
Change line in pkgIndex.tcl to:  package ifneeded tclgd 1.3 [list load [file join $dir tclgd13.dll] Tclgd]

**Comment by bovine** [comment]
Would you be able to submit the changes you had to make as a pull request?

**Comment by PaulObermeier** [comment]
Just change the pkgIndex.tcl.in file to:
package ifneeded tclgd @PACKAGE_VERSION@ \
    [list load [file join $dir @PKG_LIB_FILE@] Tclgd]
